### ISSUE TITLE
Downloading raw data with cast is not stable, and some streamed Processed Images does not have corresponding rf-frames

### ISSUE THREAD

**Issue by nguyenvuduc** [clariusdev/cast#42]
Hi Kris,

It seems the downloading raw data with Clarius Cast is not stable:
- Sometimes cusCastRequestRawData keeps returns < 0, I have to reboot the probe to make it work.
- I would like to match each RF frame with a recorded ProcessedImage (recorded by ClariusNewProcessedImageFn callback). The matching is done by the timestamp of the RF frame and the timestamp of the ProcessedImage. This is for displaying side by side the image and the rf data. However, there are a lot of RF frames are missing at the end of a recording session.

Does the Clarius probe stop buffering or rolling the buffer after the buffer is full?
How big is the rf buffer on the probe?

Attached is our tests for your reference:

- https://drive.google.com/drive/folders/1rPpDX3fvcrwvqBfcEU5ajMqem-XuVWJm?usp=sharing
- In this folder, you will find:
- (1) The statistics of missing frames. You can see the rf frames start missing after 67 image frames are recorded. And the number of missing rf-frames are correlated to the number of image frames.
- (2) The rf/image's timestamp matching result of every test. It can which sections of image frames doesn't have matched rf-frames.
![image](https://user-images.githubusercontent.com/5864656/152850975-08157087-6efe-42ee-bd40-ae8568863084.png)

Thank you,

**Comment by clariusk** [comment]
what is your probe model and version?

**Comment by nguyenvuduc** [comment]
The probe model is: C3HD
The software version is:
Clarius Cast v9.0
![image](https://user-images.githubusercontent.com/5864656/152857038-e9ba039e-0799-4cf3-86d0-93e0e26e1c26.png)

**Comment by clariusk** [comment]
Thanks, here are a few important notes, which I should probably add to the documentation.

1. The raw buffer size is 128 MB for each data set. ie. both for envelope and RF for RF mode imaging, or envelope and IQ for B mode imaging
2. The buffer is circular and will drop the oldest frame once it has reached the maximum - RF will fill up faster in most cases than the envelope buffer since the data size is much larger, but this depends on the ROI (which was added in version 8)
3. During any time that the probe goes into no contact mode (ie. lower frame rate to conserve power), RF frames are not acquired, and thus timestamps acquired for processed images may not match since no corresponding raw data exists.
4. Once a request has been made, the buffer is flushed on the probe's side. So if subsequent requests are made through the API, or if the App is used to make a request, the data will no longer exist. This is purposely done to manage the memory used for packing the raw data for sending over the wireless network.
5. New raw data can be acquired within the buffer with unfreezing
6. Requests should only be made once imaging has stopped (frozen), otherwise there may be issues in trying to stream and send over the buffer at the same time. Note this is allowed over the API, but results could be very inconsistent.
7. The first few frames when starting imaging (on an unfreeze) may be missing due to internal buffer allocation. You should plan for up to 0.5 seconds of data to be missing at the start.

**Comment by nguyenvuduc** [comment]
Thank Kris for the details,

It makes sense for me now. It explains why rf-timestamps are not matched for all of the images.

However, I still feel confused about the 128 MB raw buffer size. The raw data that I downloaded from the probe never exceed 70 rf-frames (which is about 70 frames * 72 lines * 784 samples * 2 bytes = 7MBytes). The envelopes will need 70 frames * 592 * 192 = 7 MBytes. Look like the probe doesn't effectively use all the raw buffer?

**Comment by clariusk** [comment]
i'll run some tests checking the timestamping, however what happens when you pass 0's as your start and end time, this should acquire all data in the buffer for the period you ran the acquisition.

**Comment by nguyenvuduc** [comment]
Thank Kris,
All the tests that we did use 0 as the start time and 0 as the end time.

**Comment by clariusk** [comment]
Double checked the buffer sizes:
- Envelope: 64MB
- IQ: 128MB
- RF: 192MB

Running buffering tests and downloading over the Cast API, I am able to acquire all data as expected:
- Small Parts L7
- RF Mode - Streaming Off
- Ran for 60 seconds @ 20 FPS and got all RF data within default ROI - about 1200 frames.
- The raw envelope did wrap around since the buffer is smaller, and evidently the frame size is much larger than RF when now using the ROI - so only 220 frames or 10 seconds of data available - but you're getting these same images over the API in real-time in any case.

**Comment by nguyenvuduc** [comment]
Thank Kris. I appreciate it.
We will repeat the test on our side, with both cast API and Clariub Mobile App raw data upload,
and will let you know the result. 
Regards,

**Comment by nguyenvuduc** [comment]
Look like it is my bad. It seems I made a deadlock or alternate the behaviour when calling cusRequestRawData on another thread and wait for the callback on the main thread
![image](https://user-images.githubusercontent.com/5864656/154214794-c4d5677e-365e-4964-942c-f42b66571d95.png)

**Comment by clariusk** [comment]
thanks Duc for the update, in any case, I've made some changes in version 9.2.0 of our software (April readiness) to better adjust the buffering used on the probe, so it will hopefully be more stable to ensure data can be acquired - or at least notify when there is a memory error - I discovered that what can happen is memory resources can be too limited when acquiring very large datasets, which results in some of the compression operations to fail, and just returning a message saying no data is available
