### ISSUE TITLE
Qt-Gui initialization in clariusInitListener

### ISSUE THREAD

**Issue by ccpp** [clariusdev/cast#7]
When performing a test on our continuous integration we found that the linux library breaks it, because it wants to connect to a display in `clariusInitListener`.

There is a work-around specifying `QT_QPA_PLATFORM=minimal` before initialization. However, there is no obvious reason for the library to connect to a display.

Does the library initialize a `QApplication`? If yes, can it be turned into a `QCoreApplication`?

**Comment by clariusk** [comment]
Thanks for the question. Yes, the Listen library uses Qt internally, so there is actually QGuiApplication spun to run the message loop (actually every platform behaves a bit differently, and this has to be handled case-by-case). We may not be able to convert to a QCoreApplication due to some GL code used internally, so for headless CI, you may have to go the route you mentioned, or you can spin a virtual screen similar to what's documented here: http://elementalselenium.com/tips/38-headless

**Comment by ccpp** [comment]
Thank you.
Based on your input we found that the library cannot be used on headless, and also my approach passing a different platform does not work when connecting to an actual probe due to missing createPlatformOpenGLContext.
